name: eval_summ
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - tensorflow
  - pytorch
  - pandas
  - sentence-transformers
  - pip:
      - spacy==3.4.4
      - nltk
      - tensorflow_datasets
      - neuralcoref
      - rouge
      - transformers
